name: school_app
description: "School Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_it: ^7.7.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.6.0
  cached_network_image: ^3.4.1
  injectable: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/dashboard/

  fonts:
    - family: sourcesanspro
      fonts:
        - asset: assets/fonts/source_sans_pro.ttf
