name: school_app
description: "School Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_it: ^7.7.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.6.0
  cached_network_image: ^3.4.1
  injectable: ^2.4.4
  carousel_slider: ^5.0.0
  http: ^1.2.2
  lottie: ^2.2.0
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/dashboard/
    - assets/loading.json
    - assets/translations/

  fonts:
    - family: sourceSansThree
      fonts:
        - asset: assets/fonts/source_sans_3/SourceSans3-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_sans_3/SourceSans3-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_3/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_3/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/source_sans_3/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_3/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_3/SourceSans3-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/source_sans_3/SourceSans3-Black.ttf
          weight: 900
    - family: notoSansKhmer
      fonts:
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans_khmer/NotoSansKhmer-Black.ttf
          weight: 900